### ISSUE TITLE
Similarity of two drawings

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layvo#3]
One particular metric we'd like to measure for drawings of two similar graphs (or the same graph) is the similarity of their drawings. This is especially useful when measuring how successful an incremental layout is performed without destroying the user's mental map. Details are to be provided in a separate document.

**Comment by ugurdogrusoz** [comment]
Nicely done. A few improvements:
- Rename "Show Large Graph" to "Show a larger compound graph"
- Make the label font size for larger graph much smaller (or shorten node labels if possible, get rid of all "104"s?)
- Show only two places after the decimal point in displaying metrics
- Rename "Mean Angle Difference in Degrees" to "Mean Angle Difference"
- Change the texts for mean values to mention their units (distance -> pixels, angle -> degrees)
- Put tooltips for these mean buttons to say "Mean angle difference in degrees between all node pairs at the same level (i.e., same parent graph)" and "Mean position difference in pixes between all node pairs at the same level (i.e., same parent graph)"

**Comment by ugurdogrusoz** [comment]
- "Mean position difference in pixes" -> "Mean position difference in pixels" (missing "l" in pixels; my mistake)
- "Randomize Layout of the Graph" -> "Randomize Layout"
- Can we increase wheel sensitivity? Zooms in/out too quickly.
- Why do I get only 4 edge crossings here, not 5? 
![Screenshot 2021-03-20 110842](https://user-images.githubusercontent.com/3874988/111863806-adc97100-896e-11eb-9807-689068847924.png)

**Comment by hasanbalci** [comment]
@canbax A possible performance improvement in the calculation of edge crossings suggested once by @alihanokka during his CoSEP test runs: Instead of accessing edge endpoints each time by using cy functions, storing them in an array once and accessing from there decreases the calculation time significantly. For example, if there are n edges, we need to compare an edge with n-1 edges. Instead of calling sourceEndpoint and targetEndpoint functions in cy n-1 times for an edge, we store these values in two separate arrays and access from these arrays n-1 times.

I also noticed in the last commit that instead of edge endpoints used previously, positions of source and target nodes of an edge are used in crossing calculation. I think this is a matter of choice whether we will count edges that pass through nodes as crossing or not. In cytoscape.js, edges can have different type of endpoints where outside-to-node is the default. @ugurdogrusoz What do you think about this?

**Comment by canbax** [comment]
Yes, such caching should make it faster. 

Based on the decision of using edge endpoints or positions of the source and target node, I can make those caching. 

I think I should have continued using edge endpoints because the sizes of nodes could be large. They might be compound nodes. When I'm implementing, I didn't think about it thoroughly.

**Comment by ugurdogrusoz** [comment]
As I specified "For this to work nicely, distances should be calculated from clipping point to clipping point (not center to center) as the layout algorithms strive to output ideal edge length between clipping points."
Caching would be a good improvement as well.

**Comment by canbax** [comment]
I did some caching on the method `findNumberOfCrosses`. I see that it is not much. With 1000 nodes it was like 2500 ms, now it is like 2200 ms. 
[g_01000_03.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-layvo/files/6187658/g_01000_03.txt)

However, with 400 nodes I see it become 20ms from 180ms. It seems much faster.
[g_00400_02_compound.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-layvo/files/6187666/g_00400_02_compound.txt)

Also, I didn't check the other functions. Actually, there might be some improvements on others if it's needed.

**Comment by ugurdogrusoz** [comment]
I noticed we do not have any edges to compound nodes in our larger demo graph. Can we make the following changes please:
- "n4-n7" -> "n4->c2"
- "n2-n0" -> "n2->c0"

**Comment by ugurdogrusoz** [comment]
When nodes are on top of each other edge length statistics become "null".
<img width="946" alt="Screen Shot 2021-03-23 at 13 01 18" src="https://user-images.githubusercontent.com/3874988/112128904-ed46c600-8bd7-11eb-9fc5-7b3e44f0ba4a.png">

**Comment by ugurdogrusoz** [comment]
Calculations are still funky I think. First I put all nodes overlapping (4.02 average edge length despite all nodes overlapping!):
<img width="470" alt="Screen Shot 2021-03-23 at 15 56 49" src="https://user-images.githubusercontent.com/3874988/112149812-6fdb7f80-8bf0-11eb-9ffe-ce20e8709677.png">
Then I moved E a little apart:
<img width="484" alt="Screen Shot 2021-03-23 at 15 57 04" src="https://user-images.githubusercontent.com/3874988/112149820-71a54300-8bf0-11eb-8ed9-e654fc4cb3c5.png">

**Comment by canbax** [comment]
I checked the calculations and numbers. They look fine. I think the problem happens when nodes overlap.
![image](https://user-images.githubusercontent.com/8426741/112260522-25531500-8c7b-11eb-928a-dfb5cc5ef0c0.png)

To fix this, we can try to detect if nodes overlap. Or we can just ignore this because mathematically the calculations are simply right.

**Comment by ugurdogrusoz** [comment]
I see, then we should additionally check if nodes overlap. If they do, we should take the edge length as zero.

**Comment by ugurdogrusoz** [comment]
Can we please have one last change (use rectangles for simple nodes instead of ellipses) so the users will not be surprised to have an overlap due to shapes being considered as rectangles like below:
![image](https://user-images.githubusercontent.com/3874988/112281483-24c87780-8c97-11eb-82f2-ac4f7b2b274d.png)
