### ISSUE TITLE
Overlapping edges not counting as edge crossing

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-layvo#5]
In the below example, there is an edge between A-B and B-C, but number of edge crossings returns as 1 by ignoring this overlapping edges.
![image](https://user-images.githubusercontent.com/22586369/115221457-5dcaff00-a112-11eb-9307-fd94b108eb0b.png)

**Comment by ugurdogrusoz** [comment]
Looks like when one edge is completely over the other one, we do not detect a crossing.

**Comment by canbax** [comment]
[This commit](https://github.com/iVis-at-Bilkent/cytoscape.js-layvo/commit/eda531f9522fa3a9632444a1f1093624642d9c13) solves for exact overlapping. Since edges also have widths, they might seem like overlapping but they might not be overlapping exactly. Do we need to care for edge widths as well?

For example points (100, 100), (199.99, 99.99), (300, 100) don't overlap since the numbers don't match exactly.

**Comment by ugurdogrusoz** [comment]
No let's not worry about edge width, assume a unit of 1 width.
