### ISSUE TITLE
Calculating metrics on a sub-graph

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layvo#9]
Let's change the related API so that it takes optional node and edge lists and makes the calculations only on the subgraph made up by these lists (i.e., take a node into account if and only if the node is in the node list; take an edge into account if and only if the edge is in the edge list). We assume that if an edge e=(a,b) is in the edge list, its source and target nodes are in the node list but not vice versa.

**Comment by hamzaislam101** [comment]
After this commit, we can pass an array of nodes and edges to the `generalProperties` method as an optional parameter. If no parameter is passed, layvo will use all the nodes and edges in the cytoscape instance. If nodes and edges are passed then instead of fetching nodes and edges from cytoscape instance, the values passed would be used to calculate metrics.

**Comment by ugurdogrusoz** [comment]
Thanks. You should update the README accordingly.

**Comment by hamzaislam101** [comment]
Updated.
